# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Carpentry for Pharmacists
description:      'Teaching the tools to get computers to do cool science'
url:              http://drlabratory.github.io/semester-pharmacy
baseurl:          /semester-pharmacy
email:            jeramia.ory@stlcop.edu

feedbackurl:      https://goo.gl/forms/WGZ6la1DCv8hSPf93
author:
  name:           'Jeramia Ory'
  url:            https://twitter.com/drlabratory

github:
  repo:           https://github.com/drlabratory/semester-pharmacy
  #               Be sure the 'Issues' feature is activated in 'Settings'
